FROM ubuntu:18.04 

ENV JAVA_HOME=/usr/local/jdk1.8.0_151 \
    PATH=/usr/local/jdk1.8.0_151/bin:$PATH \
    TIMEZONE=Asia/Shanghai \
    LANG=zh_CN.UTF-8

RUN echo "${TIMEZONE}" > /etc/timezone \
    && echo "$LANG UTF-8" > /etc/locale.gen \
    && apt-get update -q \
    && ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && mkdir -p /home/jenkins/.jenkins \
    && mkdir -p /home/jenkins/agent \
    && mkdir -p /usr/share/jenkins \
    && mkdir -p /root/.kube

COPY jdk1.8.0_151 /usr/local/jdk1.8.0_151
COPY kubectl /usr/local/bin/kubectl
COPY docker  /usr/local/bin/docker
COPY jenkins-slave /usr/local/bin/jenkins-slave
COPY slave.jar /usr/share/jenkins

# java/字符集/DinD/svn/jnlp
RUN  mkdir /usr/java -p \
     && ln -s /usr/local/jdk1.8.0_151 /usr/java/jdk1.8.0_151 \
     && apt-get install -yq curl apt-utils dialog locales  apt-transport-https build-essential bzip2 ca-certificates  sudo jq unzip zip gnupg2 software-properties-common \
     && update-locale LANG=$LANG \
     && locale-gen $LANG \
     && apt-get upgrade -y \
     && groupadd -g 10000 jenkins \
     && useradd -c "Jenkins user" -d $HOME -u 10000 -g 10000 -m jenkins \
     && usermod -a -G docker jenkins \
     && sed -i '/^root/a\jenkins    ALL=(ALL:ALL) NOPASSWD:ALL' /etc/sudoers

USER root

WORKDIR /home/jenkins

ENTRYPOINT ["jenkins-slave"]
