kind: Service
apiVersion: v1
metadata:
  name: polling-server
  namespace: test 
  labels:
    ref: dev 
spec:
  selector:
    app: polling-server
  type:  ClusterIP
  ports:
  - name: api-port
    port: 8080
    targetPort:  api
